### ISSUE TITLE
Add an option to also remove favorites

### ISSUE THREAD

**Issue by Natim** [brndnmtthws/tweet-delete#2]
Thank you for the lib. I was able to remove my old tweets with few interactions.
I think it might makes sense to also remove the favorites I made on other's people tweets.
Do you think that something we could add to that lib too?

https://stackoverflow.com/q/42607007/186202

**Comment by mrichman** [comment]
Would LOVE to see this feature. Thanks!

**Comment by brndnmtthws** [comment]
Since there are 2 of you I'll spend some time figuring this out. I guess it would useful for myself too :)

**Comment by brndnmtthws** [comment]
In theory it should work now (I'll publish a release soon), however I need to test it first which will take some time.

**Comment by brndnmtthws** [comment]
Weird, let me check to make sure it's actually working. I might have missed something.

For `--minimum_engagement`, it will *only* delete the tweets that have less than the specified engagement value. It's calculated here: https://github.com/brndnmtthws/tweet-delete/blob/master/tweet_delete/deleter.py#L127-L128

It counts a retweet and 2 engagements, and a like/favourite as 1 engagement. So if you set it to 3, it'll only delete tweets that have less than 1 retweet and 1 like, or 3 likes, or 2 retweets.

**Comment by brndnmtthws** [comment]
@mrichman to follow up, the only reason I can think that it's not working for you is that you either a) aren't running the latest version or b) you're being rate limited by the Twitter API (this could happen if you did a lot of deletes already).

This is what I see in my logs:

<img width="759" alt="Screen Shot 2020-09-10 at 12 47 50 PM" src="https://user-images.githubusercontent.com/3129093/92766052-e0f9ca80-f363-11ea-9f0e-ae4cfff3a271.png">

**Comment by mrichman** [comment]
My guess is I've been rate limited, though it's been a few days. I'm on version 0.2.3. Do you know how long you're "blacklisted" for once rate limited?
